filter:
    paths:
        - 'src/*'
checks:
    php:
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true

coding_style:
    php: {  }


build:
    environment:
        php:
            version: 7.4
    tests:
        override:
            -
                command: './vendor/bin/phpunit --config tests/phpunit.xml --coverage-clover=tests/clover.xml'
                coverage:
                    file: 'tests/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage: false
