filter:
    paths: ['src/*']

build:
    environment:
        php:
            version: 8.1
    tests:
        override:
            - php-scrutinizer-run --enable-security-analysis
            -   command: 'XDEBUG_MODE=coverage ./vendor/bin/phpunit --config tests/phpunit.xml --coverage-clover=tests/clover.xml'
                coverage:
                    file: 'tests/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage: false