#sudo: false
dist: focal

addons:
  apt:
    update: true

language: php
php:
  - 8.1.2

before_script:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml
